version: '3.2'
services:
  web:
    build: '.'
    image: 'wordpress_ernesto:latest'
    depends_on:
      - mysql
    ports:
      - "8000:80"
    restart: always
  mysql:
    image: 'mysql'
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wordpress_db
      MYSQL_USER: wordpress_user
      MYSQL_PASSWORD: wordpress_pass
    ports:
      - "9000:3306"
    restart: always
